# Generated by Django 4.2.27 on 2025-12-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('x_user_id', models.CharField(max_length=50, unique=True)),
                ('x_username', models.CharField(max_length=50)),
                ('x_name', models.CharField(max_length=100)),
                ('access_token_encrypted', models.BinaryField()),
                ('refresh_token_encrypted', models.BinaryField()),
                ('token_expires_at', models.DateTimeField()),
                ('scopes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'X User',
                'verbose_name_plural': 'X Users',
            },
        ),
    ]
