# Generated by Django 4.2.27 on 2025-12-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuser',
            name='following_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='xuser',
            name='liked_tweets_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='xuser',
            name='seeded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
