# Generated by Django 4.2.27 on 2025-12-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
